name: core
version: 16-2
summary: snapd runtime environment
description: The core runtime environment for snapd
confinement: strict
type: os
grade: stable

hooks:
  configure:
    plugs:
      - core-support
      - network-bind

parts:
  hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  livebuild:
    source: .
    plugin: make
    build-packages:
      - livecd-rootfs
      - pyflakes3
      - shellcheck
      - gawk
